# Generated by Django 3.2.9 on 2022-01-12 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_visual_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
