# Generated by Django 3.2.9 on 2022-01-14 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_visual_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cursorsize',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='user',
            name='fontsize',
            field=models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
