runtime: python
entrypoint: gunicorn -b :$PORT main:app
env: flex

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: linen-works-328605:us-central1:fisi-room