# Generated by Django 3.2.9 on 2021-12-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='owner',
        ),
    ]
