# Generated by Django 3.2.9 on 2021-12-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
