# Generated by Django 3.2.9 on 2021-12-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default=None, upload_to='asd'),
            preserve_default=False,
        ),
    ]
