# Generated by Django 3.2.9 on 2021-12-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to='courses/<built-in function id>'),
        ),
    ]
