# Generated by Django 3.2.9 on 2022-01-05 03:44

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=classroom.models.homework_storage_path),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=classroom.models.post_storage_path),
        ),
    ]
